import "../globals.css";
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import {Header} from "@/components/layout/Header";
import Providers from "@/app/providers/ApolloProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body style={{margin:0}}>
          <AppRouterCacheProvider >
              <Header />
              <div className={'container mt-5 mx-auto'}>
                  <Providers>
                    {children}
                  </Providers>
              </div>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
